import type { ThemeName } from "@/types/event";

export interface ThemeTokens {
  label: string;
  colors: { background: string; surface: string; text: string; muted: string; primary: string; accent: string; line: string };
  fonts: { display: string; body: string };
  decoration: string[];
  background: string;
}

export const themes: Record<ThemeName, ThemeTokens> = {
  elegant: { label: "Elegant", colors: { background: "#f7f5f0", surface: "#fffefa", text: "#262820", muted: "#77796e", primary: "#65735b", accent: "#d8b87a", line: "#e7e4db" }, fonts: { display: "'Iowan Old Style', 'Palatino Linotype', Georgia, serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["✳", "✦", "❋"], background: "radial-gradient(ellipse at 12% 12%, #e5eadf 0, transparent 34%), linear-gradient(135deg,#f8f7f2,#f0eee7)" },
  luxury: { label: "Luxury", colors: { background: "#11110f", surface: "#1c1b18", text: "#f7f1e5", muted: "#b2a995", primary: "#c5a15b", accent: "#eee0bd", line: "#39362e" }, fonts: { display: "'Bodoni MT', Didot, 'Times New Roman', serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["✧", "✦", "◇"], background: "radial-gradient(ellipse at 50% 0%, #39301e 0, transparent 45%), #11110f" },
  floral: { label: "Floral", colors: { background: "#fbf5f2", surface: "#fffdfb", text: "#44343b", muted: "#8d7982", primary: "#a9677c", accent: "#d7ae82", line: "#eddee1" }, fonts: { display: "'Iowan Old Style', Georgia, serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["❀", "✿", "❋"], background: "radial-gradient(ellipse at 0% 0%, #f2dfe3, transparent 45%), radial-gradient(ellipse at 100% 90%, #e6e9d9, transparent 42%), #fbf5f2" },
  kids: { label: "Kids", colors: { background: "#fff9ed", surface: "#ffffff", text: "#24334c", muted: "#66758c", primary: "#ff8a54", accent: "#ffd35b", line: "#f3e4c8" }, fonts: { display: "'Trebuchet MS', sans-serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["★", "●", "✦"], background: "radial-gradient(circle at 12% 15%,#ffe9a5 0 8%,transparent 8.5%), radial-gradient(circle at 88% 80%,#ffd9ce 0 10%,transparent 10.5%), #fff9ed" },
  minions: { label: "Aventura amarilla", colors: { background: "#fffbe6", surface: "#ffffff", text: "#202b3d", muted: "#637084", primary: "#f4c900", accent: "#3975ad", line: "#f1e5ac" }, fonts: { display: "'Trebuchet MS', sans-serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["✦", "●", "★"], background: "radial-gradient(ellipse at 14% 4%,#fff0a8,transparent 38%),linear-gradient(145deg,#fffbe6,#f2f7fc)" },
  superheroes: { label: "Superheroes", colors: { background: "#f1f5ff", surface: "#ffffff", text: "#142442", muted: "#65728a", primary: "#e34c52", accent: "#f0be39", line: "#dbe4f3" }, fonts: { display: "'Arial Black', 'Trebuchet MS', sans-serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["✦", "⚡", "★"], background: "radial-gradient(circle at 88% 12%,#d8e7ff,transparent 35%),linear-gradient(135deg,#f6f8ff,#eaf0ff)" },
  princess: { label: "Princess", colors: { background: "#fff6fb", surface: "#fffefe", text: "#4b3155", muted: "#927d99", primary: "#bc7eb5", accent: "#e6c575", line: "#f0deed" }, fonts: { display: "'Iowan Old Style', Georgia, serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["✧", "♡", "✿"], background: "radial-gradient(ellipse at 50% 0%,#f4dff1,transparent 48%),linear-gradient(140deg,#fff9fd,#f8eff9)" },
  space: { label: "Space", colors: { background: "#10182e", surface: "#18233e", text: "#f5f7ff", muted: "#adb8d4", primary: "#8d85ff", accent: "#5cdbdc", line: "#303d5d" }, fonts: { display: "'Trebuchet MS', sans-serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["✦", "·", "✧"], background: "radial-gradient(circle at 15% 20%,#36316d 0 1px,transparent 2px),radial-gradient(circle at 75% 70%,#43c9d2 0 1px,transparent 2px),radial-gradient(ellipse at 50% 0%,#242d5c,#10182e 65%)" },
  safari: { label: "Safari", colors: { background: "#f4f3e9", surface: "#fffef9", text: "#34372c", muted: "#777963", primary: "#68734b", accent: "#d69a55", line: "#e1dfd0" }, fonts: { display: "'Trebuchet MS', sans-serif", body: "'Avenir Next', Avenir, sans-serif" }, decoration: ["❋", "✦", "❧"], background: "radial-gradient(ellipse at 90% 0%,#e5e6c7,transparent 42%),radial-gradient(ellipse at 0% 100%,#eddfc9,transparent 45%),#f4f3e9" }
};
