import { CommonModule, NgOptimizedImage } from '@angular/common';
import { CountdownSectionComponent } from './countdown.component';
import { OpenDataComponent } from '../integrations/open-data.component';
import { ChangeDetectionStrategy, Component, computed, inject, input, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { EventConfig } from '../../core/invitation.models';
import { ThemeRegistryService } from '../themes/theme-registry.service';

@Component({ selector:'is-invitation-view', standalone:true, imports:[CommonModule,NgOptimizedImage,ReactiveFormsModule,CountdownSectionComponent,OpenDataComponent], changeDetection:ChangeDetectionStrategy.OnPush,
  template:`
  <main class="invite-page" [ngStyle]="themeVars()" [attr.data-theme]="config().theme">
    <nav class="invite-nav"><a [href]="'#'" class="invite-brand">{{ config().hostName }}</a><a class="invite-nav-cta" href="#confirmar">{{ config().eventType === 'commercial' ? 'Solicitar información' : 'Confirmar asistencia' }}</a></nav>
    <section class="invite-hero" id="inicio"><div class="invite-hero-copy"><p class="invite-kicker">{{ config().eventType === 'commercial' ? 'MÚSICA · CELEBRACIÓN · TRADICIÓN' : 'UNA CELEBRACIÓN MUY ESPECIAL' }}</p><h1>{{ config().title }}</h1><p class="invite-subtitle">{{ config().subtitle }}</p><p class="invite-description">{{ config().description }}</p>@if (config().date) { <a class="invite-button" href="#detalles">Descubrir los detalles <span>↓</span></a> }</div><div class="invite-art" [class.has-image]="config().heroImage">@if(config().heroImage;as heroImage){<img [ngSrc]="heroImage" width="960" height="1100" priority [alt]="config().title">} @else {<div class="art-ring"></div><span class="art-symbol">{{ config().eventType === 'birthday' ? '✹' : '✺' }}</span><span class="art-initial">{{ config().title.charAt(0) }}</span>}<span class="art-caption">{{ config().location }}</span></div></section>
    @if (config().sections.countdown && config().date) { <section class="invite-section countdown-section"><p class="invite-kicker">FALTA MUY POCO</p><is-countdown [date]="config().date" [time]="config().time" [timezone]="config().timezone"/></section> }
    @if (config().sections.story && config().story.length) { <section class="invite-section story-section"><p class="invite-kicker">NUESTRA HISTORIA</p><h2>Un momento para<br><em>recordar juntos.</em></h2><div class="story-list">@for (item of config().story; track item.title) {<article><span>{{ themeDecoration() }}</span><div><h3>{{ item.title }}</h3><p>{{ item.body }}</p></div></article>}</div></section> }
    @if (config().sections.details) { <section class="invite-section details-section" id="detalles"><p class="invite-kicker">GUARDA LA FECHA</p><h2>{{ config().eventType === 'commercial' ? 'Música para tu ocasión' : 'Nos encantará verte' }}</h2><div class="detail-cards"><article><span>FECHA</span><strong>{{ config().date ? formatDate(config().date) : 'Por definir' }}</strong>@if (config().time) {<small>{{ config().time }} h</small>}</article><article><span>LUGAR</span><strong>{{ config().location }}</strong>@if(config().address){<small>{{ config().address }}</small>}</article>@if(config().eventType !== 'commercial'){<article><span>ANFITRIÓN</span><strong>{{ config().hostName }}</strong><small>Será un gusto celebrar contigo</small></article>}</div>@if(config().sections.map && config().mapUrl){<a class="invite-text-link" [href]="config().mapUrl" target="_blank" rel="noopener">Abrir ubicación en Maps ↗</a>}</section> }
    @if (config().sections.timeline && config().timeline.length) { <section class="invite-section"><p class="invite-kicker">AGENDA DEL DÍA</p><h2>Cada momento cuenta.</h2><ol class="invite-timeline">@for(item of config().timeline;track item.time+item.title){<li><time>{{item.time}}</time><div><b>{{item.title}}</b>@if(item.description){<p>{{item.description}}</p>}</div></li>}</ol></section> }
    @if (config().sections.gallery && config().gallery.length) { <section class="invite-section gallery-section"><p class="invite-kicker">MOMENTOS PARA COMPARTIR</p><h2>Un vistazo a la celebración.</h2><div class="invite-gallery">@for(photo of config().gallery;track photo.src){<figure><img [ngSrc]="photo.src" width="840" height="680" loading="lazy" [alt]="photo.alt"><figcaption>{{photo.caption}}</figcaption></figure>}</div></section> }
    @if (config().sections.gifts && config().gifts.enabled) { <section class="invite-section gift-section"><p class="invite-kicker">UN DETALLE CON CARIÑO</p><h2>Gracias por pensar en nosotros.</h2><p>{{config().gifts.message}}</p><div class="gift-links">@for(gift of config().gifts.links;track gift.url){<a [href]="gift.url" target="_blank" rel="noopener">{{gift.label}} ↗</a>}</div></section> }
    @if (config().sections.rsvp && config().rsvp.enabled) { <section class="invite-section rsvp-section" id="confirmar"><div><p class="invite-kicker">TU RESPUESTA NOS AYUDA</p><h2>{{ config().eventType === 'commercial' ? 'Hablemos de tu evento.' : '¿Nos acompañas?' }}</h2><p>Completa tus datos para preparar una respuesta por WhatsApp.</p></div><form [formGroup]="form" (ngSubmit)="submit()" novalidate><label>Tu nombre<input formControlName="name" autocomplete="name" placeholder="Nombre y apellido"></label><label>¿Podrás acompañarnos?<select formControlName="attending"><option value="">Selecciona</option><option value="yes">¡Sí, ahí estaré!</option><option value="no">Esta vez no podré</option></select></label>@if(form.controls.attending.value==='yes'){<label>Número de personas<input type="number" formControlName="guests" min="1" max="20"></label>}<label>Mensaje (opcional)<textarea formControlName="comments" rows="3" maxlength="300" placeholder="Un mensaje para los anfitriones"></textarea></label>@if(form.invalid && attempted()){<p class="invite-form-error" role="alert">Escribe tu nombre y selecciona si asistirás.</p>}@if(complete()){<p class="invite-form-success" role="status">{{config().rsvp.successMessage || 'Tu respuesta está lista.'}} @if(config().rsvp.whatsappNumber){<a [href]="responseUrl()" target="_blank" rel="noopener">Enviar respuesta por WhatsApp ↗</a>} @else {<span>El organizador debe agregar un teléfono de contacto para recibirla.</span>}</p>}<button type="submit" class="invite-button">{{config().eventType==='commercial'?'Solicitar información':'Confirmar asistencia'}} ↗</button><small>La respuesta se enviará por WhatsApp si el organizador configuró su número.</small></form></section> }
    @if (config().sections.music && config().music.enabled && config().music.src) { <section class="invite-music"><span>♪ {{config().music.title}}</span><audio controls preload="none"><source [src]="config().music.src">Tu navegador no soporta audio.</audio></section> }
    @if(config().sections.openData && config().openData.enabled && (config().openData.jikan || config().openData.pokeApi)){<section class="invite-section api-section"><p class="invite-kicker">UN EXTRA PARA DIVERTIRSE</p>@defer (on viewport) { <is-open-data [jikan]="config().openData.jikan" [pokeApi]="config().openData.pokeApi"/> } @placeholder { <div class="api-placeholder" aria-hidden="true"></div> }</section>}
    <section class="invite-qr"><p>Comparte la invitación</p><img [src]="qrUrl()" width="120" height="120" alt="Código QR para abrir esta invitación" loading="lazy"><small>Escanéame para volver</small></section>
    <footer class="invite-footer"><span>{{themeDecoration()}}</span><p>{{config().hostName}}</p><small>{{config().eventType==='commercial'?'Música para celebrar.': 'Con cariño, te esperamos.'}}</small></footer>
  </main>` })
export class InvitationViewComponent {
  readonly config = input.required<EventConfig>();
  private readonly themes = inject(ThemeRegistryService);
  readonly themeVars = computed(() => this.themes.variables(this.config()));
  readonly themeDecoration = computed(() => this.themes.get(this.config().theme).decoration);
  readonly attempted = signal(false);
  readonly complete = signal(false);
  private readonly fb = inject(FormBuilder);
  readonly form = this.fb.nonNullable.group({ name:['', [Validators.required,Validators.minLength(2)]], attending:['',Validators.required], guests:[1,[Validators.min(1),Validators.max(20)]], comments:[''] });
  responseUrl(): string { const c=this.config(); const d=this.form.getRawValue(); const phone=c.rsvp.whatsappNumber?.replace(/\D/g,'')||''; const message=`Hola, soy ${d.name}. ${d.attending==='yes'?'Sí asistiré':'No podré asistir'}${d.attending==='yes'?` con ${d.guests} persona(s)`:''}. ${d.comments}`; return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`; }
  readonly qrUrl = computed(() => { const target=typeof window!=='undefined'?window.location.href:`${this.config().slug}`; return `https://api.qrserver.com/v1/create-qr-code/?size=240x240&margin=8&data=${encodeURIComponent(target)}`; });
  formatDate(value: string): string { const [year,month,day]=value.split('-').map(Number); return new Intl.DateTimeFormat('es-MX',{dateStyle:'full',timeZone:'UTC'}).format(new Date(Date.UTC(year,month-1,day,12))); }
  submit(): void { this.attempted.set(true); if(this.form.invalid)return; this.complete.set(true); if(this.config().rsvp.whatsappNumber) window.open(this.responseUrl(), '_blank', 'noopener,noreferrer'); }
}
