import { ChangeDetectionStrategy, Component, inject, input, signal } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { OpenDataService } from '../../core/open-data.service';
@Component({ selector:'is-open-data', standalone:true, changeDetection:ChangeDetectionStrategy.OnPush, template:`<div class="api-picks"><h2>Pequeños descubrimientos</h2><p>Contenido opcional de fuentes de datos abiertas.</p><div class="api-actions">@if(jikan()){<button type="button" (click)="loadAnime()" [disabled]="busy()">{{busy()?'Buscando…':'Recomendación de anime'}}</button>}@if(pokeApi()){<button type="button" (click)="loadPokemon()" [disabled]="busy()">{{busy()?'Buscando…':'Descubre un Pokémon'}}</button>}</div>@if(result();as item){<article><strong>{{item.title}}</strong><p>{{item.description}}</p>@if(item.image){<img [src]="item.image" [alt]="item.title" width="140" height="140" loading="lazy">}</article>}@if(error()){<p role="status">No pudimos cargar el contenido ahora. Inténtalo más tarde.</p>}</div>` })
export class OpenDataComponent {
  readonly jikan=input(false); readonly pokeApi=input(false); readonly busy=signal(false); readonly result=signal<{title:string;description:string;image?:string}|null>(null); readonly error=signal(false); private readonly api=inject(OpenDataService);
  async loadAnime(){this.busy.set(true);this.error.set(false);try{const {data}=await firstValueFrom(this.api.currentAnime());const item=data[0];if(!item)throw new Error('Respuesta sin resultados');this.result.set({title:item.title,description:item.synopsis||'Una recomendación para descubrir.',image:item.images.jpg?.image_url});}catch{this.error.set(true);}finally{this.busy.set(false);}}
  async loadPokemon(){this.busy.set(true);this.error.set(false);try{const data=await firstValueFrom(this.api.pokemon());this.result.set({title:`${data.name} · #${data.id}`,description:`Tipo: ${data.types.map(type=>type.type.name).join(', ')}`,image:data.sprites.other?.['official-artwork']?.front_default||undefined});}catch{this.error.set(true);}finally{this.busy.set(false);}}
}
