import { ArrowDown, ArrowRight, Check, Clock3, Guitar, MapPin, Music2, Phone, ShieldCheck, Star } from "lucide-react";
import { Reveal } from "@/components/Reveal";
import { BookingForm } from "@/components/BookingForm";
import { WhatsappButton } from "@/components/WhatsappButton";
import mariachi from "../../data/mariachi.json";

const wa = `https://wa.me/${mariachi.whatsappNumber}?text=${encodeURIComponent(mariachi.whatsappMessage)}`;
const services = [
  ["Serenatas románticas", "Una canción puede decir lo que las palabras no alcanzan.", "♥"],
  ["Cumpleaños", "Celebra rodeado de familia, amigos y música que todos cantan.", "✳"],
  ["XV años", "Un momento inolvidable para una noche que merece ser única.", "✺"],
  ["Bodas y aniversarios", "Acompañamos historias de amor en sus momentos más especiales.", "∞"],
  ["Graduaciones", "El sonido de una meta cumplida merece celebrarse en grande.", "✦"],
  ["Eventos empresariales", "Un toque mexicano auténtico para recibir y sorprender.", "♬"],
];
const repertoire = ["Rancheras", "Boleros", "Huapangos", "Corridos tradicionales", "Música romántica", "Canciones para serenata"];
const municipalities = ["Nezahualcóyotl", "Chimalhuacán", "Los Reyes La Paz", "Ixtapaluca", "Chalco", "Valle de Chalco", "Texcoco", "Ecatepec"];

export default function HomePage() {
  return <main>
    <header className="nav-shell"><a className="brand" href="#inicio" aria-label="Mariachi Mexicanísimo, inicio"><span className="brand-mark">M<span>✦</span></span><span>MARIACHI <b>MEXICANÍSIMO</b></span></a><nav aria-label="Navegación principal"><a href="#servicios">Servicios</a><a href="#repertorio">Repertorio</a><a href="#cobertura">Cobertura</a></nav><a className="nav-cta" href="#reservar">Cotiza tu evento <ArrowRight size={16}/></a></header>
    <section className="hero" id="inicio"><div className="hero-content"><p className="eyebrow"><span className="eyebrow-line"/> TRADICIÓN QUE SE SIENTE</p><h1>Mariachi<br/><em>Mexicanísimo</em></h1><p className="hero-lead">Llevamos la auténtica música mexicana a tus momentos más importantes.</p><p className="hero-copy">Serenatas, cumpleaños, bodas, aniversarios y eventos especiales con músicos profesionales.</p><div className="hero-actions"><a className="button button-red" href={wa} target="_blank" rel="noreferrer">Reservar por WhatsApp <ArrowRight size={17}/></a><a className="button button-outline" href="#reservar">Solicitar cotización</a></div><div className="hero-trust"><span><MapPin/> Zona Oriente, Edo. Méx.</span><span><Clock3/> Atención inmediata</span><span><ShieldCheck/> Músicos profesionales</span></div></div><div className="hero-art" aria-label="Ilustración artística de una guitarra y ornamentos mexicanos" role="img"><div className="hero-sun"/><div className="arch arch-outer"/><div className="arch arch-inner"/><div className="hero-star star-a">✦</div><div className="hero-star star-b">✧</div><div className="guitar-art"><div className="guitar-neck"/><div className="guitar-body"><div className="guitar-hole"/><div className="guitar-bridge"/></div></div><div className="hero-stamp"><span>EL SONIDO</span><b>DE MÉXICO</b><span>PARA TU CELEBRACIÓN</span></div><div className="hero-ribbon">MÚSICA · ALEGRÍA · TRADICIÓN</div></div><a className="scroll-cue" href="#servicios" aria-label="Descubrir servicios"><ArrowDown size={17}/></a></section>
    <section className="intro-band"><span className="intro-rule"/><p>{mariachi.slogan}</p><span className="intro-rule"/></section>
    <section className="section section-services" id="servicios"><Reveal><div className="section-head"><p className="eyebrow">CELEBRAMOS CONTIGO</p><h2>Una ocasión especial.<br/><em>Un recuerdo para siempre.</em></h2><p>Hay momentos que merecen una banda sonora propia. Nosotros ponemos la música; tú, la emoción.</p></div></Reveal><div className="service-grid">{services.map(([title,copy,icon],i)=><Reveal key={title} delay={i*.06}><article className="service-card"><span className="service-index">0{i+1}</span><span className="service-icon">{icon}</span><h3>{title}</h3><p>{copy}</p><a href="#reservar" aria-label={`Cotizar ${title}`}>Cotizar este servicio <ArrowRight size={15}/></a></article></Reveal>)}</div></section>
    <section className="manifesto"><div className="manifesto-art"><span className="manifesto-sun"/><Guitar className="manifesto-guitar" strokeWidth={1}/><span className="manifesto-caption">HECHO PARA<br/>CANTARSE JUNTOS</span></div><div className="manifesto-copy"><p className="eyebrow">MÁS QUE MÚSICA</p><h2>El mariachi reúne.<br/><em>La música permanece.</em></h2><p>Desde la primera nota hasta el último coro, cada presentación está pensada para crear ese instante en que todos se acercan, sonríen y cantan juntos.</p><p>Tradición mexicana interpretada con respeto, energía y atención a los detalles de tu celebración.</p><a className="text-link" href={wa} target="_blank" rel="noreferrer">Cuéntanos qué celebras <ArrowRight size={16}/></a></div></section>
    <section className="section repertoire" id="repertorio"><Reveal><div className="section-head"><p className="eyebrow">UN REPERTORIO PARA CADA HISTORIA</p><h2>Clásicos que <em>se sienten.</em></h2><p>¿Tienes una canción especial? Cuéntanos y revisamos contigo las opciones para tu evento.</p></div></Reveal><div className="repertoire-list">{repertoire.map((item,i)=><Reveal key={item} delay={i*.05}><div className="repertoire-item"><span className="rep-num">0{i+1}</span><Music2 size={19}/><span>{item}</span><span className="rep-star">✦</span></div></Reveal>)}</div><a className="button button-outline repertoire-cta" href={wa} target="_blank" rel="noreferrer">Preguntar por una canción <ArrowRight size={16}/></a></section>
    <section className="quote-band"><div className="quote-ornament">❝</div><p>La tradición mexicana que hace inolvidable cada celebración</p><span>MARIACHI MEXICANÍSIMO</span></section>
    <section className="section coverage" id="cobertura"><Reveal><div className="coverage-heading"><div><p className="eyebrow">CERCA DE TI</p><h2>La fiesta llega<br/><em>a tu municipio.</em></h2></div><p>Atendemos eventos en la Zona Oriente del Estado de México. Compártenos tu ubicación y fecha para confirmar cobertura y disponibilidad.</p></div></Reveal><div className="coverage-card"><div className="coverage-map"><div className="map-halo"/><MapPin className="map-pin" size={42}/><span className="map-label label-one">TEXCOCO</span><span className="map-label label-two">ECATEPEC</span><span className="map-label label-three">CHALCO</span><span className="map-label label-four">NEZA</span><span className="map-caption">ZONA ORIENTE<br/>ESTADO DE MÉXICO</span><a href="https://www.google.com/maps/search/Zona+Oriente+Estado+de+M%C3%A9xico" target="_blank" rel="noreferrer" className="map-open">Explorar en Maps <ArrowRight size={15}/></a></div><div className="coverage-list"><p className="eyebrow">MUNICIPIOS</p><h3>¿Dónde nos vemos?</h3><div className="municipality-grid">{municipalities.map((name)=><span key={name}><Check size={15}/>{name}</span>)}</div><div className="coverage-note"><MapPin size={18}/><p>¿Tu municipio no aparece? <a href={wa} target="_blank" rel="noreferrer">Pregúntanos por WhatsApp.</a></p></div></div></div></section>
    <section className="section reviews" id="experiencias"><Reveal><div className="review-inner"><div className="review-stars" aria-label="Experiencias de clientes"><Star/><Star/><Star/><Star/><Star/></div><p className="eyebrow">CADA EVENTO TIENE SU HISTORIA</p><h2>La próxima canción<br/><em>podría ser la tuya.</em></h2><p>Estamos preparando este espacio para compartir experiencias reales de nuestras familias y anfitriones. ¿Ya nos escuchaste? Nos encantará conocer tu historia.</p><a className="text-link" href={wa} target="_blank" rel="noreferrer">Comparte tu experiencia <ArrowRight size={16}/></a></div></Reveal></section>
    <section className="booking" id="reservar"><div className="booking-intro"><p className="eyebrow">EMPECEMOS A PLANEAR</p><h2>Tu celebración<br/><em>merece música.</em></h2><p>Cuéntanos los detalles y te contactamos por WhatsApp para revisar opciones, cotización y disponibilidad.</p><div className="booking-points"><span><Check size={16}/> Atención personalizada</span><span><Check size={16}/> Cotización según tu evento</span><span><Check size={16}/> Confirmación directa contigo</span></div><a href="tel:+525515332499" className="phone-link"><Phone size={18}/> ¿Prefieres llamar? <b>55 1533 2499</b></a></div><BookingForm/></section>
    <footer className="footer"><a className="brand brand-footer" href="#inicio"><span className="brand-mark">M<span>✦</span></span><span>MARIACHI <b>MEXICANÍSIMO</b></span></a><p>{mariachi.slogan}</p><div><a href={wa} target="_blank" rel="noreferrer">WhatsApp</a><a href="tel:+525515332499">55 1533 2499</a><a href="#cobertura">Zona Oriente, Estado de México</a></div><small>© {new Date().getFullYear()} Mariachi Mexicanísimo. Música para celebrar.</small></footer>
    <WhatsappButton/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"LocalBusiness",name:"Mariachi Mexicanísimo",description:mariachi.slogan,telephone:"+52 1 55 1533 2499",areaServed:municipalities.map(name=>({"@type":"City",name,address:{"@type":"PostalAddress",addressRegion:"Estado de México",addressCountry:"MX"}})),knowsAbout:repertoire})}}/>
  </main>;
}
